logging:
  level:
    root: info
  file:
    path: /home/ec2-user/api/log

  logback:
    rolling policy:
      max-history: 7

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: buttersis13!
  jpa:
    hibernate:
      ddl-auto: update #create , create-drop , update , validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    open-in-view: false
  url:
    base: http://localhost:8081
  config:
    activate:
      on-profile: dev